language: go
go:
  - 1.8
  - 1.9
  - 1.10
  - master
sudo: false
before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
  - glide install
before_script:
  - go vet ./...
script:
  - $GOPATH/bin/goveralls -service=travis-ci
